### DISCUSSION TITLE
Paperless - Use network mount as media/data/config folder not working

### DISCUSSION THREAD

**Discussion by elahd** [alexbelgium/hassio-addons#673] [Q&A]
I'm running into trouble having the Paperless addon use a network mount for data storage. Settings are as follows:

In the addon's config UI:
`networkdisks`: `//192.168.1.5/Paperless`
`CONFIG_LOCATION`: `/config/addons_config/paperless_ng/config.yaml`

In `/config/addons_config/paperless_ng/config.yaml`:
```yaml
PAPERLESS_CONSUMPTION_DIR: /mnt/Paperless/consume
PAPERLESS_DATA_DIR: /mnt/Paperless
PAPERLESS_MEDIA_ROOT: /mnt/Paperless/media
```

It looks like the the config.yaml entries are overridden by [these lines](https://github.com/alexbelgium/hassio-addons/blob/3121a0e8248f4914c3d3ecc3a359aedf2e24ef97/paperless_ngx/Dockerfile#L43-L46) in the Dockerfile. Running `printenv` from a shell in the addon's container returns the locations from the Dockerfile, not from my config file.

Are these folders deliberately hard coded? Is there a way to get the Paperless addon to use network mounts for consumption, data, and media?

Thanks!
