### ISSUE TITLE
[Request resilio] networkdisks and localdisks options in ResilioSync

### ISSUE THREAD

**Issue by zoiv** [alexbelgium/hassio-addons#104]
Would it be possible, as you did for other addons, to add the possibility to mount networkdisks and localdisks inside resilio docker, and having these options available inside homeassistant interface ? 

Thanks a lot for your help !

**Comment by alexbelgium** [comment]
Hello, a new version is pushed with the options!

```yaml
GUID: user
GPID: user
TZ: timezone
localdisks: sda1 #put the hardware name of your drive to mount separated by commas, or its label. Ex: sda1, sdb1, MYNAS...
networkdisks: "//SERVER/SHARE" # optional, list of smb servers to mount, separated by commas
cifsusername: "username" # optional, smb username, same for all smb shares
cifspassword: "password" # optional, smb password
cifsdomain: "domain" # optional, allow setting the domain for the smb share
```
