### ISSUE TITLE
✨ [REQUEST] Addon Linkace

### ISSUE THREAD

**Issue by b52src** [alexbelgium/hassio-addons#1262]
### Checked

- [X] If a new addon, I have checked on  Google that such as addon doesn't already exists
- [X] If a new feature, I have searched in the discussions & issues that it was not already covered

### Which addon?

linkace is a selfhosted bookmark archive. I have been able to get it running unofficially deploying from portainer within Home assistant however it would be nice to have as an official adon.
 https://www.linkace.org/docs/v1/setup/setup-with-docker/
https://www.linkace.org/#install 

### Is your feature request related to a problem? Please describe

no

### Describe the solution you'd like

official linkace addon in repo, there dose not appear to be a good selfhosted bookmark archive available as an addon

**Comment by b52src** [comment]
example compose file being used currently 
dockerhub image: https://hub.docker.com/r/linkace/linkace/

```
version: "3"

services:

  # --- MariaDB
  db:
    image: mariadb:10.7
    restart: unless-stopped
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    environment:
      - MYSQL_ROOT_PASSWORD=passwordhere
      - MYSQL_USER=linkace
      - MYSQL_PASSWORD=passwordhere
      - MYSQL_DATABASE=linkacedb
    volumes:
      - db:/var/lib/mysql

  # --- LinkAce Image with PHP and nginx
  app:
    image: linkace/linkace:simple
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - 8085:80
      #- "0.0.0.0:443:443"
    environment:
      - APP_KEY=base64:LB9H2gVx2Kr6r1nHKYzmkkP2gosyfViq6cNn6zeOygbwT0=
      - DB_HOST=db
      - DB_DATABASE=linkacedb
      - DB_USERNAME=linkace
      - DB_PASSWORD=passwordhere
      - SETUP_COMPLETED=true
    volumes:
      - linkace_logs:/app/storage/logs
      # Remove the hash of the following line if you want to use HTTPS for this container
      #- ./nginx-ssl.conf:/etc/nginx/conf.d/default.conf:ro
      #- /path/to/your/ssl/certificates:/certs:ro
      # Remove the hash of the following line if you want to use local backups
      #- ./backups:/app/storage/app/backups


volumes:
  linkace_logs:
  db:
    driver: local
```
