### ISSUE TITLE
✨ [REQUEST] Photoview

### ISSUE THREAD

**Issue by anduchs** [alexbelgium/hassio-addons#1323]
### Checked

- [X] If a new addon, I have checked on  Google that such as addon doesn't already exists
- [X] If a new feature, I have searched in the discussions & issues that it was not already covered

### Which addon?

Photoview: https://photoview.github.io/

### Is your feature request related to a problem? Please describe

No

### Describe the solution you'd like

It would be great to have this in your repos.

I've already done a quick&dirty addon, but I guess you want to adapt it to your typical layout.
Also I don't know if I chose the right directories for everything.

Dockerfile:
```
FROM viktorstrate/photoview:master

ENV PHOTOVIEW_DATABASE_DRIVER=sqlite \
    PHOTOVIEW_LISTEN_IP=photoview \
    PHOTOVIEW_LISTEN_PORT=80 \
    PHOTOVIEW_SQLITE_PATH=/share/photoview/photoview.db \
    PHOTOVIEW_MEDIA_CACHE=/share/photoview/cache

VOLUME ["/share", "/media"]
```

config.yaml:
```
name: Photoview
description: Photoview
version: 0.0.3
slug: photoview
arch:
  - amd64
ports:
  80/tcp: 8001
ports_description:
  80/tcp: "Web Interface"
map:
  - "share:rw"
  - "media:ro"
```

Also, an alternative docker-repo might be: viktorstrate/photoview:2.3.13 (latest upstream release)
