### ISSUE TITLE
[Inadyn] Cloudfare proxied option?

### ISSUE THREAD

**Issue by deku-m** [alexbelgium/hassio-addons#192]
**Which addon?**

* Addon name : Inadyn
* Addon version : 2.9.1-3

**Describe the bug**

When using this app to update the cloudfare there is an option named proxied which you can use to update the record to proxied in cloudfare website. Im not sure if it is in the addon or the application itself but it doesnt work. This is a new feature from 2.8 as i could see same as TTL 

**YAML CONFIG:**
```
  - provider: cloudflare.com
    username: sitename.nl
    password: <secret>
    hostname: subdomein.sitename.nl
    proxied: true
```

**Inadyn (from troglobit):**
```
# Create a unique custom API token with the following permissions:
# -> Zone.Zone - Read, Zone.DNS - Edit.
provider cloudflare.com {
    username = zone.name
    password = api_token_important_read_comment
    hostname = hostname.zone.name
    ttl = 1 # optional, value of 1 is 'automatic'.
    proxied = false # optional.
}
```

Could it be that this isnt pushed from the docker config?
in rootfs/templates/inadyn.mustache under (marked ** xxx ** as this might be it):
```
{{#providers}}
{{#custom_provider}}custom{{/custom_provider}}{{^custom_provider}}provider{{/custom_provider}} {{provider}} {
    username         = "{{username}}"{{#password}}
    password         = "{{password}}"{{/password}}{{#ssl}}
    ssl              = {{ssl}}{{/ssl}}
    hostname         = "{{hostname}}"{{#checkip_ssl}}
    checkip-ssl      = {{checkip_ssl}}{{/checkip_ssl}}{{#checkip_server}}
    checkip-server   = "{{checkip_server}}"{{/checkip_server}}{{#checkip_command}}
    checkip-command  = "{{checkip_command}}"{{/checkip_command}}{{#checkip_path}}
    checkip-path     = "{{checkip_path}}"{{/checkip_path}}{{#user_agent}}
    user-agent       = "{{user_agent}}"{{/user_agent}}{{#wildcard}}
    wildcard         = "{{wildcard}}"{{/wildcard}}{{#ddns_server}}
    ddns-server      = "{{ddns_server}}"{{/ddns_server}}{{#ddns_path}}
    ddns-path        = "{{ddns_path}}"{{/ddns_path}}{{#append_myip}}
    append-myip      = "{{append_myip}}"{{/append_myip}}
    **proxied       = "{{proxied}}"{{/proxied}}**
    **ttl       = "{{ttl}}"{{/ttl}}**
}
{{/providers}}
```
**and config.json:**
```
"schema": {
    "providers": [
      {
           "proxied": "bool?"
           "ttl": "int?"

```

**To Reproduce**

```
providers:
  - provider: default@strato.com:1
    username: sitename.nl
    password: <secret>
    hostname: subdomein.sitename.nl
  - provider: default@strato.com:2
    username: sitename.nl
    password: <secret>
    hostname: subdomein.sitename.nl
  - provider: default@strato.com:3
    username: sitename.nl
    password: <secret>
    hostname: subdomein.sitename.nl
  - provider: default@strato.com:4
    username: sitename.nl
    password: <secret>
    hostname: subdomein.sitename.nl
  - provider: default@strato.com:5
    username: sitename.nl
    password: <secret>
    hostname: subdomein.sitename.nl
  - provider: cloudflare.com
    username: sitename.nl
    password: <secret>
    hostname: subdomein.sitename.nl
    proxied: true
```
**System**

* Supervisor version:  supervisor-2021.12.2
* Host system version:  core-2021.12.10
