### ISSUE TITLE
Mariadb 

### ISSUE THREAD

**Issue by aladin2000** [alexbelgium/hassio-addons#199]
Hi 
I have a question rfegarding such an error

```
[cont-init.d] 99-mariadb_discovery.sh: executing... 
[13:26:15] WARNING: MariaDB addon was found! It can't be configured automatically, but you can configure it manually using those values in the initial set-up :
Database user : service
Database password : hiden
Database name : nextcloud
Host-name : core-mariadb:3306
[cont-init.d] 99-mariadb_discovery.sh: exited 0.
```
I tested a bash from the container itself and Mariadb container could be 'pinged'
 using the core-mariadb  name Port is open also. 
 
SO what could be  the 'manual' fix for that error ?
Where these lines has to be put ?
Do I have to reinstall the addon ? 

```
PUID: 1000
PGID: 1000
use_own_certs: false
certfile: fullchain.pem
keyfile: privkey.pem
data_directory: /share/nextcloud
trusted_domains: hiden
OCR: false
OCRLANG: fra
Full_Text_Search: false
elasticsearch_server: <ip:port>
database user: service
database password: <  for nextcloud >
database name: nextcloud
host-name: core-mariadb:3306
TZ: Europe/Paris
```
Fom core-mariadb  addon itself I created the params

```
databases:
  - homeassistant
  - nextcloud
logins:
  - username: service
    password: < idem as  for  nextcloud >
rights:
  - username: service
    database: nextcloud
  - username: hiden
    database: homeassistant
    privileges:
      - SELECT
```
