### ISSUE TITLE
[inadyn] forced-update settings is not working

### ISSUE THREAD

**Issue by lbouriez** [alexbelgium/hassio-addons#241]
**Which addon?**

- Addon name : Inadyn
- Addon version : 2.9.1-6

**Describe the bug**
I am trying to setup cloudfare and I used the forced-update parameter, I get this error:

```
/etc/cont-init.d/99-run.sh: executing
/etc/inadyn.conf:4: invalid integer value for option 'forced-update'
Parse error in /etc/inadyn.conf
/etc/cont-init.d/99-run.sh: exiting 1
```

**To Reproduce**

My configuration is:

```
providers:
  - provider: cloudflare.com
    username: XX.org
    password: XX
    hostname: XX.YY.org
forced_update: true
```

**Comment by alexbelgium** [comment]
Hi @x1pher and @deku-m, as I know you're using the addon, are you using forced_update? Thanks!

**Comment by alexbelgium** [comment]
Mmh I think you need to use : 
```yaml
providers:
  - provider: cloudflare.com
    username: XX.org
    password: XX
    hostname: XX.YY.org
    forced_update: true
```
