### ISSUE TITLE
🐛 [Arpspoof] Addon won't start

### ISSUE THREAD

**Issue by martindinicolino** [alexbelgium/hassio-addons#575]
**Which addon?**
- Addon name : Arpspoof
- Addon version : 1.0.0

**Describe the bug**
This addon won't start, I have two instances of HomeAssistant (one at my parent's and one at my place) and the same thing happens on both.
When I start the addon, it appears to be running, but the web UI remains unreachable, the addon's cpu and memory usage remains at 0% and the addon page displays the "Start" button again, after i refresh the page (no matter how long i wait before doing so).
I believe the addon never actually started. Please let me know if i am messing something up. Any help is highly appreciated.

**To Reproduce**
This happens every time i try to start the addon.

**Full addon log**

```
Starting...
/etc/cont-init.d/00-banner.sh: executing
-----------------------------------------------------------
 Add-on: Arpspoof
 block internet connection for local network devices
-----------------------------------------------------------
 Add-on version: 1.0.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 9.3  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2022.11.4
 Home Assistant Supervisor: 2022.11.2
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums
 https://github.com/alexbelgium/hassio-addons
-----------------------------------------------------------
/etc/cont-init.d/00-global_var.sh: executing
ROUTER_IP='192.168.4.1'
/etc/cont-init.d/01-custom_script.sh: executing
[15:25:48] INFO: Execute if existing custom script /config/arpspoof.sh
[15:25:48] INFO: ... no script found
/etc/cont-init.d/99-run.sh: executing
/./etc/cont-init.d/99-run.sh: line 6: INTERFACE_NAME: unbound variable
/etc/cont-init.d/99-run.sh: exiting 1
```

**Full addon config**

`<ROUTER_IP: 192.168.4.1>`

**Comment by alexbelgium** [comment]
Hi, thanks, solved

**Comment by alexbelgium** [comment]
I'll close this as tested working, but do comment if it doesn't

**Comment by martindinicolino** [comment]
thank you for fixing it this quickly, I am now able to run the addon 👍

when looking at the web UI i only get a blank page reading „Number five is alive!“ - I was expecting an interface where to set up some settings (the installation guide for the addon reads something among the lines of open the webUI and adapt the software options)
did i mess something up?
so far i was unable to find any mention/documentation in regards to the web UI page i am getting; i‘ll keep looking but i would highly appreciate it, if someone could point me in the right direction

**Comment by martindinicolino** [comment]
yes, I read through that, but i'm clearly missing something, because if i try and block a device on my network by running `http://192.168.4.xxx:7022/disconnect?ip=192.168.4.yyy` the logs show the following error
```
2022-11-25 15:46:22.088 | INFO     | __main__:get_status:25 - Getting state for ip: 192.168.4.yy
2022-11-25 15:46:22.090 | ERROR    | __main__:get_status:41 - must be str, not NoneType
192.168.4.zz - - [25/Nov/2022 15:46:22] "GET /status?ip=192.168.4.yy HTTP/1.1" 200 -
```
and the device is still able to access the web

**Comment by alexbelgium** [comment]
Hi @gieljnssns and @Stooovie, I think you are using this addon would you have an advice for the issue advice? Thanks!

**Comment by gieljnssns** [comment]
```yaml
- platform: command_line
  switches:
    nmac_internet:
      friendly_name: "Mac mini internet"
      command_off: "/usr/bin/curl -X GET http://192.168.79.54:7022/disconnect?ip=192.168.79.24"
      command_on: "/usr/bin/curl -X GET http://192.168.79.54:7022/reconnect?ip=192.168.79.24"
      command_state: "/usr/bin/curl -X GET http://192.168.79.54:7022/status?ip=192.168.79.24"
      value_template: >
        {{ value != "1" }}
```
