### ISSUE TITLE
🐛 [Immich] Add-on does not start

### ISSUE THREAD

**Issue by furang** [alexbelgium/hassio-addons#742]
**Which addon?**

- Addon name : Immich
- Addon version : 1.49.0

**Describe the bug**
Add-on does not start

**To Reproduce**

1. Install add-on
2. Start add-on 

**Full addon log**
```
exec /init: exec format error
```

**Full addon config**
```yaml
JWT_SECRET: <secret here>
PGID: 1000
PUID: 1000
TZ: Europe/Paris
data_location: /share/immich
```

**System**

- Supervisor version: 2023.01.1
- Host system version: Home Assistant OS 9.5
