### ISSUE TITLE
token_bad_formatted

### ISSUE THREAD

**Issue by aladin2000** [alexbelgium/hassio-addons#84]
Add-on version: 0.6.0-8
 You are running the latest version of this add-on.
 System: Raspbian GNU/Linux 10 (buster)  (armv7 / raspberrypi3)
 Home Assistant Core: 2021.11.3
 Home Assistant Supervisor: 2021.10.8

```
2021-11-14 14:52:47.185200 - INFO  : Get contract :
2021-11-14 14:52:47.186525 - INFO  :  => Query Cache
2021-11-14 14:52:47.201718 - DEBUG :  MQTT Send : Enedis/21........20/contract/error => 0
2021-11-14 14:52:47.203076 - DEBUG : {'error_code': True, 'detail': {'message': {'error': 'token_bad_formatted', 'description': 'Ton token est mal formaté.', 'alert_user': True}}}
2021-11-14 14:52:47.204560 - DEBUG :  MQTT Send : Enedis/error => 1
2021-11-14 14:52:47.207189 - DEBUG :  MQTT Send : Enedis/errorMsg/message => {'error': 'token_bad_formatted', 'description': 'Ton token est mal formaté.', 'alert_user': True}
2021-11-14 14:52:47.208225 - INFO  : -- Stop import --
2021-11-14 14:52:47.209841 - INFO  : 
```

Le ACCESS-TOKEN est le même que celui de myenedis et de la card Myenedis 
Le meme Token fonctionne avec la methode curl proposé par le site Gateway.

Info complémentaire: J'ai utilisé la version docker sur un host en dehors de HA et ensuite sur le meme raspberry hors HA , le token est bien accepté  dans les deux cas...
et l'app se connecte chez Enedis, jusque atteinte du quota de 50 requetes... je ne peux plus tester plus loin mais le logs contient bien les access au data de consommation 

Bizarrerie ....

**Comment by alexbelgium** [comment]
Merci ! Serait-il possible d'avoir la totalité du Log de l'addon ? Il commence par le texte 00-aaa.sh

Merci d'avance

**Comment by aladin2000** [comment]
> Merci ! Serait-il possible d'avoir la totalité du Log de l'addon ? Il commence par le texte 00-aaa.sh
> 
> Merci d'avance
J'ai masqué une partie de la valeur du Token ainsi qu'une partie de valeur du PDL

00-aaa.sh
00-banner.sh
-----------------------------------------------------------
 Add-on: Enedisgateway2mqtt
 use Enedis Gateway API to send data in your MQTT Broker
-----------------------------------------------------------
 Add-on version: 0.6.0-8
 You are running the latest version of this add-on.
 System: Raspbian GNU/Linux 10 (buster)  (armv7 / raspberrypi3)
 Home Assistant Core: 2021.11.3
 Home Assistant Supervisor: 2021.10.8
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
 https://github.com/alexbelgium/hassio-addons
-----------------------------------------------------------
09-run.sh
[17:13:35] INFO: All variables defined in the addon will be exported to the config file located in /config/enedisgateway2mqtt
[17:13:46] INFO: Starting the app with the variables in /config/enedisgateway2mqtt
REFRESH_CONTRACT=false
ACCESS_TOKEN=tYctEXss...............................I77Nm5eoxys29LZ
CARD_MYENEDIS=true
CONSUMPTION_PRICE_BASE=0.1443
DEBUG=true
GET_CONSUMPTION=true
GET_CONSUMPTION_DETAIL=true
HA_AUTODISCOVERY=true
HA_AUTODISCOVERY_PREFIX=homeassistant
INFLUXDB_ENABLE=true
INFLUXDB_HOST=192.168.1.7
INFLUXDB_PORT=8086
MQTT_HOST=192.168.1.7
MQTT_PASSWORD=mosquitto
MQTT_PORT=1883
MQTT_PREFIX=Enedis
MQTT_USERNAME=mosquitto
PDL=21124023033520
:13:56.505971 - INFO  : InfluxDB : Connection success
2021-11-14 17:13:56.521896 - INFO  : Check database
2021-11-14 17:13:56.524485 - INFO  :  => Connect to SQLite Database
2021-11-14 17:13:56.807016 - INFO  : ####################################################################################
2021-11-14 17:13:56.807663 - INFO  : Get contract :
2021-11-14 17:13:56.811566 - INFO  :  => Query Cache
2021-11-14 17:13:56.833644 - DEBUG :  MQTT Send : Enedis/2........33520/contract/error => 0
2021-11-14 17:13:56.834652 - DEBUG : {'error_code': True, 'detail': {'message': {'error': 'token_bad_formatted', 'description': 'Ton token est mal formaté.', 'alert_user': True}}}
2021-11-14 17:13:56.840169 - DEBUG :  MQTT Send : Enedis/error => 1
2021-11-14 17:13:56.843282 - DEBUG :  MQTT Send : Enedis/errorMsg/message => {'error': 'token_bad_formatted', 'description': 'Ton token est mal formaté.', 'alert_user': True}
2021-11-14 17:13:56.843971 - INFO  : -- Stop import --
2021-11-14 17:13:56.848918 - INFO  : ####################################################################################
2021-11-14 17:13:56.849747 - INFO  : IMPORT FINISH
2021-11-14 17:13:56.851740 - INFO  : #########################################################################

**Comment by alexbelgium** [comment]
Pourrais tu faire un test ? Vider la case ACCESS_TOKEN de l'addon, ouvrir le fichier /config/enedisgateway2mqtt/enedisgateway2mqtt.conf et mettre manuellement la ligne 
```ACCESS_TOKEN=tYctEXss...............................I77Nm5eoxys29LZ```
puis redémarrer l'addon ? Si ca ne marche pas, pourrais tu essayer avec ```ACCESS_TOKEN='tYctEXss...............................I77Nm5eoxys29LZ'``` ?

Merci d'avance !

**Comment by aladin2000** [comment]
> Pourrais tu faire un test ? Vider la case ACCESS_TOKEN de l'addon, sauver les options, ouvrir le fichier /config/enedisgateway2mqtt/enedisgateway2mqtt.conf et mettre manuellement la ligne `ACCESS_TOKEN=tYctEXss...............................I77Nm5eoxys29LZ` puis redémarrer l'addon ? Si ca ne marche pas, pourrais tu essayer avec `ACCESS_TOKEN='tYctEXss...............................I77Nm5eoxys29LZ'` ?
> 
> Merci d'avance !
Ton scenario est impossible car testés avec les deux chaines ACCESS (avec et sans quote) 

2021-11-14 18:54:01.239144 - CRITICAL : Environement variable 'ACCESS_TOKEN' is mandatory

L'addon rejette le contenu du fichier yaml qui

**Comment by alexbelgium** [comment]
OK merci c'est du à la version de l'addon il faut attendre que la propo de mise à jour apparaisse sur ton système pour qu'on puisse faire le est

**Comment by alexbelgium** [comment]
J'ai poussé une nouvelle version pourrais tu la tester ? Ça devrait être 0.6.0-12 ou 0.6.0-13

Ça va forcer le format et pourrais aider

**Comment by aladin2000** [comment]
j'ai la dernière version 0.6.0-9  
J'ai bien le TOKEN qui revient à la valeur initiale : XXX
mais lors des modifications souhaitées avec ou sans quote, le TOKEN Refuse de prendre en charge-back sans le formulaire de l'UI. et seul le TOKEN XXXX reste valide dans le addon

**Comment by alexbelgium** [comment]
Argh... Merci pour le feedback. J'ai poussé une v12 mais il faut le temps que le repo refresh et ça prend quelques heures (pour le faire manuellement il faut aller dans l'onglet superviseur, puis addons, puis cliquer en haut à droite sur les 3 petits points et recharger).

Je suis curieux, tu encode via l'ui directement (en cliquant sur le bouton afficher les options non utilisées dans la configuration) ? Ou tu édite en mode yaml sous la forme ACCESS_TOKEN: xxx ?

**Comment by aladin2000** [comment]
je tente de faire les modifs comme tu l'indiques via le fichier yamml apres ssh sur mon server  et en cas de difficulté je tente de mettre les quotes ou le token depuis l'UI via les 3 points 
Je vais refaire un build now...

**Comment by alexbelgium** [comment]
Merci pour le suivi, ce n'est pas simple...

Et sur la v12 si tu encode dans l'ui et restart ça ne marche toujours pas ?

Lorsque tu es dans les options de l'addon, si tu clique sur les trois petits points en haut à droite tu peux également éditer sous forme de yaml. A priori ça ne changera rien mais c'est plus pour info...

**Comment by aladin2000** [comment]
Et sur la v12 si tu encode dans l'ui et restart ça ne marche toujours pas ? 
non  
j'ai déja fait un copie colle ou retappé le token , rien n'y fait 
 si j'utilise l'editeur sous les 3 points les quotes disparaissent dans l'onglets options
et l'erreur reste la meme avec le token rempli  avec mon token ou rempli avec des XXX

**Comment by alexbelgium** [comment]
Merci, je regarderais encore demain...

**Comment by alexbelgium** [comment]
Quand la nouvelle logique sera implémentée (fichier config indépendant au lieu de variables à encoder une à une) le problème sera résolu à coup sûr

**Comment by aladin2000** [comment]
> Quand la nouvelle logique sera implémentée (fichier config indépendant au lieu de variables à encoder une à une) le problème sera résolu à coup sûr

Pour quand est prévue cette version ?

**Comment by alexbelgium** [comment]
A priori dans les prochains jours, les tests sont en cours...

**Comment by m4dm4rtig4n** [comment]
@aladin2000 pense à tester la 0.7.3 et nous dire si tt est bon pour toi :)

**Comment by aladin2000** [comment]
> @aladin2000 pense à tester la 0.7.3 et nous dire si tt est bon pour toi :)

bonjour

j'ai testé la v 0.7.3 avec qq difficultés sur la compatibilité de format yaml de la partie pdl...

il semble que je ne trouve pas la bonne façon de coder le format yaml ...

après plusieures tentatives, j'arrive à avoir un ensemble de variables mais jai une dernière erreur dans les logs indiquant  qu il manque des

variables, probablement dû au mauvais formttage yaml

exemple de ma config :
```

####################
## ENEDIS GATEWAY ##
####################
enedis_gateway:
- PDL_1: 2..........20  ## 14 digits##
    token: tYctE.......................................29LZ ## 55 digits
    plan: BASE # BASE or HP/HC
    consumption: true
    consumption_detail: true
    consumption_price_hc: 0
    consumption_price_hp: 0
    consumption_price_base: 0.1443
    production: false
    production_detail: false
    #    offpeak_hours: ""        # USE ONLY IF YOU WANT OVERLOAD DEFAULT VALUE, Format : 22h36-00h10;01h00-06h00
    addresses: true

```
l'autre format origine qui ne semble pas passer dans un valideur de format  yaml

```
enedis_gateway:
  PDL_1: 2..........20  ## 14 digits##
    token: tYctE.......................................29LZ ## 55 digits
    plan: BASE # BASE or HP/HC
    consumption: true
    consumption_detail: true
    consumption_price_hc: 0
    consumption_price_hp: 0
    consumption_price_base: 0.1443
    production: false
    production_detail: false
    #    offpeak_hours: ""        # USE ONLY IF YOU WANT OVERLOAD DEFAULT VALUE, Format : 22h36-00h10;01h00-06h00
    addresses: true
```

Malgré des efforts j'ai toujours qq chose comme une erreur de parsing  ou de format comme suit:

```
2021-11-17 22:28:37.040180 - ERROR : Some mandatory parameters are missing :
2021-11-17 22:28:37.040765 - ERROR : - enedis_gateway.PDL
2021-11-17 22:28:37.041101 - ERROR : 
2021-11-17 22:28:37.041428 - ERROR : You can get list of parameters here :

2021-11-17 22:28:37.041756 - ERROR :  => https://github.com/m4dm4rtig4n/enedisgateway2mqtt#configuration-file
2021-11-17 22:28:37.042083 - CRITICAL : -- Stop application --

```


j'espère que cela aide

**Comment by aladin2000** [comment]
ok j'ai fait le correctif suivant: 

```
enedis_gateway:
 "21........20":
    TZ: "Europe/Paris"
    addresses: true
.... 
```

**Comment by alexbelgium** [comment]
@m4dm4rtig4n : je dois dire que je m'y suis trompé aussi. pour le config template, ça pourrait être utile de mettre PDL1XXXXXXX au lieu de PDL_1 pour rendre plus clair que c'est cette partie qu'il faut changer

**Comment by m4dm4rtig4n** [comment]
J'ai revu la doc ce matin à ce sujet :p 

```
####################
## ENEDIS GATEWAY ##
####################
enedis_gateway:
  XXXXXXXXXXXXXX:              # Replace XXXXXXXXXXXXXX by your PDL Number. MANDATORY
    token: YOUR_TOKEN          # MANDATORY
    plan: BASE                 # BASE or HP/HC
    consumption: true                 
    consumption_detail: true         
    consumption_price_hc: 0           
    consumption_price_hp: 0           
    consumption_price_base: 0         
    production: false                 
    production_detail: false          
    offpeak_hours: ""         # USE ONLY IF YOU WANT OVERLOAD DEFAULT VALUE, Format : 22h36-06h00
    addresses: true
```
