### ISSUE TITLE
✨ [REQUEST] Channels DVR Server

### ISSUE THREAD

**Issue by nkm8** [alexbelgium/hassio-addons#858]
**Which addon?**

https://getchannels.com/dvr-server/#docker

**Is your feature request related to a problem? Please describe.**

I checked and I am unable to find an existing addon for this application, but it is extremely similar to the existing Plex and Emby addons. I also investigated using Portainer to run this container, but I need access to mount a local disk connected to HASS OS as external storage.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by nkm8** [comment]
For anyone who stumbles on this, I was able to get this working using Portainer:
```yaml
version: "3.9"
services:
  channels-dvr:
    image: fancybits/channels-dvr:tve
    container_name: channels-dvr
    network_mode: host
    ports:
      - "8089:8089"
    restart: on-failure:10
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - /mnt/data/supervisor/homeassistant/addons_config/channels-dvr:/channels-dvr
      - "/mnt/data/supervisor/share/<MOUNT NAME>/Channels DVR:/shares/channels-dvr"
```

My goal was to use local disks attached to my NUC running Home Assistant. To make this work:
- I use [sambanas](https://github.com/dianlight/hassio-addons/tree/master/sambanas) to mount the local disk as a SAMBA share
- Use the new [2023.6 feature to mount SAMBA shares to HA OS](https://www.home-assistant.io/blog/2023/06/07/release-20236/#connect-and-use-your-existing-network-storage)

This is a bit of a kludge - ideally this would exist as a native addon in this repo so that I could pass the local disks directly to the container. I'm not sure what sort of negative performance hit there is using my current workaround, but so far Channels has performed good enough.
