### ISSUE TITLE
❓ [SCRUTINY] how to access detailed smart params

### ISSUE THREAD

**Issue by dm82m** [alexbelgium/hassio-addons#895]
How to access the detailed smart parameters like „reallocated sector count“. Not able to get it extracted with template sensor… 😫

**Comment by alexbelgium** [comment]
Hi, sorry I don't know as this is relates to the app itself and not the add-on... Perhaps you would have more chances asking on the app github repo. And I can help if there is anything linked to the add-on

**Comment by dm82m** [comment]
found the solution, maybe you can put that into the readme as example:

```
rest:
  - verify_ssl: false
    scan_interval: 60
    resource: http://192.168.178.4:8086/api/device/0x57c35481f82a7a9c/details
    sensor:
      - name: "HDD - WWN"
        value_template: "{{ value_json.data.smart_results[0].device_wwn }}"
      - name: "HDD - Last Update"
        value_template: "{{ value_json.data.smart_results[0].date }}"
        device_class: timestamp
      - name: "HDD - Temperature"
        value_template: "{{ value_json.data.smart_results[0].temp }}"
        device_class: temperature
        unit_of_measurement: "°C"
        state_class: measurement
      - name: "HDD - Power Cycles"
        value_template: "{{ value_json.data.smart_results[0].power_cycle_count }}"
      - name: "HDD - Power Hours"
        value_template: "{{ value_json.data.smart_results[0].power_on_hours }}"
      - name: "HDD - Protocol"
        value_template: "{{ value_json.data.smart_results[0].device_protocol }}"
      - name: "HDD - Reallocated Sectors Count"
        value_template: '{{ value_json.data.smart_results[0].attrs["5"].raw_value }}'
      - name: "HDD - Reallocation Event Count"
        value_template: '{{ value_json.data.smart_results[0].attrs["196"].raw_value }}'
      - name: "HDD - Current Pending Sector Count"
        value_template: '{{ value_json.data.smart_results[0].attrs["197"].raw_value }}'
      - name: "HDD - (Offline) Uncorrectable Sector Count"
        value_template: '{{ value_json.data.smart_results[0].attrs["198"].raw_value }}'
    binary_sensor:
      - name: "HDD - SMART Status"
        value_template: "{{ bool(value_json.data.smart_results[0].Status) }}"
        device_class: problem
```
